### PR TITLE
Rustic redesign

### PR DESCRIPTION
**Pull request by maxwofford**
@zachlatta This is still in progress. Would love to get your input on the design so far!

### CODE REVIEW

**Comment by quackduck** [comment]
@zachlatta what do you think?

**Comment by zachlatta** [comment]
I think it's super cool, but going to stick with the current design for the archived site. Here's a screenshot of the beaut Max made in this PR for posterity:

image

**Comment by quackduck** [comment]
Haha! Did your scheme work?

**Comment by zachlatta** [comment]
Yes! I'll update the README

--
Zach Latta
https://zachlatta.com <http://zachlatta.com>
@zachlatta <https://twitter.com/zachlatta> / fb
<https://www.facebook.com/crynix> / github <https://github.com/zachlatta>

**Pull request closed without merging**
